fix

diff --git a/xtheme b/xtheme
--- a/xtheme
+++ b/xtheme
@@ -88,7 +88,7 @@ rgb_from_hex() {
     local color=${1/\#/}
     printf "%d %d %d" \
         0x${color:0:2} 0x${color:2:2} 0x${color:4:2} \
-        || fatal "Invalid hex value"
+        || fatal "Invalid hex value ${1}"
 }
 
 rgb_to_hex() {
@@ -258,17 +258,23 @@ import_image_colors() {
         $(convert "$image" +dither -colors 16 -unique-colors txt:- | grep -E -o " \#.{6}" 2>$STDERR || fatal)
     )
 
+    echo ${colors[*]} >&2
+    echo ">>>> ${colors[15]}" >&2
+
+    local l=${#colors[*]}
+    echo ">>>> $l" >&2
+
     background=$(rgb value ${colors[0]}  12)
-    foreground=$(rgb value ${colors[15]} 78)
+    foreground=$(rgb value ${colors[$(( $l - 1 ))]} 78)
 
     color0=$(rgb value ${colors[0]} 17)
-    color1=${colors[9]}
-    color2=${colors[10]}
-    color3=${colors[11]}
-    color4=${colors[12]}
-    color5=${colors[13]}
-    color6=${colors[14]}
-    color7=$(rgb value ${colors[15]} 88)
+    color1=${colors[$(( $l - 7 ))]}
+    color2=${colors[$(( $l - 6 ))]}
+    color3=${colors[$(( $l - 5 ))]}
+    color4=${colors[$(( $l - 4 ))]}
+    color5=${colors[$(( $l - 3 ))]}
+    color6=${colors[$(( $l - 2 ))]}
+    color7=$(rgb value ${colors[$(( $l - 1 ))]} 88)
 }
 
 modify_colors() {
