fix

diff --git a/xtheme b/xtheme
--- a/xtheme
+++ b/xtheme
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 
 LC_ALL=C
-BASE="$(dirname "${BASH_SOURCE:-$0}")"
+# using as library?
+[[ "${0}" != "${BASH_SOURCE}" ]] && \
+    RGB_IS_LIB=true || RGB_IS_LIB=
 
 # -----------------------------------------------------------------------------
 # Defaults
@@ -14,7 +16,12 @@ THEME_COLOR_SCALE=${THEME_COLOR_SCALE:-+15}
 THEME_IMPORT_SCALE=${THEME_IMPORT_SCALE:-+18}
 
 PREFER_DARK_THEME=1
+
 # -----------------------------------------------------------------------------
+xrdbq() {
+    xrdb -query | grep -w "${1}:" | tail -n1 | cut -f 2
+}
+
 min() {
     printf "%s\n" $@ | sort -g | head -n1 2>/dev/null
 }
@@ -117,7 +124,6 @@ hsv_to_rgb() {
     fatal "Invalid conversion"
 }
 
-
 rgb_value() {
     local HSV=( $(rgb_to_hsv ${1}) )
     local v=${HSV[2]}; [[ $v -gt 100 ]] && v=100
@@ -138,14 +144,11 @@ rgb_value() {
 }
 
 # -----------------------------------------------------------------------------
-# Color-palette functions
+# Color-management functions
 # -----------------------------------------------------------------------------
-xrdbq() {
-    xrdb -query | grep -w "${1}:" | tail -n1 | cut -f 2
-}
-
 # Clear all color-variables
 clear_colors() {
+    local i
     background=
     foreground=
     cursor=
@@ -157,6 +160,7 @@ clear_colors() {
 
 # Import colors from xrdb config
 import_xrdb_colors() {
+    local i
     background=$(xrdbq background)
     foreground=$(xrdbq foreground)
     cursor=$(xrdbq cursor)
@@ -166,29 +170,50 @@ import_xrdb_colors() {
     done
 }
 
+import_theme_colors() {
+    local scheme="$(find_resource ${2:-theme} "${1/\~/$HOME}" 2>/dev/null)"
+
+    [[ ! "${scheme}" ]] \
+        && scheme="$(find_resource ${2:-theme} "${1/\~/$HOME}.sh" 2>/dev/null)"
+
+    [[ ! "${scheme}" ]] \
+        && fatal "theme '${1}' not existing!"
+
+    source "$scheme" \
+        || fatal "theme '${1}' not imported!"
+}
+
+merge_theme_colors() {
+    import_theme_colors "${1}" merge
+}
+
 import_image_colors() {
+    local image="${1/\~/$HOME}"
 	local colors
 
 	type -p convert >/dev/null 2>&1 \
 		|| fatal "imagemagick not found"
 
+    [[ -e "$image" ]] \
+		|| fatal "image '${1}' not found"
+
     colors=(
-        $(convert "${1}" +dither -colors 16 -unique-colors txt:- | grep -E -o " \#.{6}" 2>/dev/null)
+        $(convert "$image" +dither -colors 16 -unique-colors txt:- | grep -E -o " \#.{6}" 2>/dev/null || fatal)
     )
 
     color0=$(rgb_value ${colors[0]} $THEME_IMPORT_SCALE)
-    color1=${colors[8]} 
-    color2=${colors[9]}
-    color3=${colors[10]}
-    color4=${colors[11]}
-    color5=${colors[12]}
-    color6=${colors[13]}
+    color1=${colors[9]};
+    color2=${colors[10]}
+    color3=${colors[11]}
+    color4=${colors[12]}
+    color5=${colors[13]}
+    color6=${colors[14]}
     color7=${colors[15]}
 }
 
 
 refill_colors() {
-    local color
+    local i color
 
     # black
     color0=${color0:-#282a2e}
@@ -207,14 +232,10 @@ refill_colors() {
     # white
     color7=${color7:-#707880}
 
-    color8=${color8:-$(rgb_value $color0 $THEME_COLOR_SCALE)}
-    color9=${color9:-$(rgb_value $color1 $THEME_COLOR_SCALE)}
-    color10=${color10:-$(rgb_value $color2 $THEME_COLOR_SCALE)}
-    color11=${color11:-$(rgb_value $color3 $THEME_COLOR_SCALE)}
-    color12=${color12:-$(rgb_value $color4 $THEME_COLOR_SCALE)}
-    color13=${color13:-$(rgb_value $color5 $THEME_COLOR_SCALE)}
-    color14=${color14:-$(rgb_value $color6 $THEME_COLOR_SCALE)}
-    color15=${color15:-$(rgb_value $color7 $THEME_COLOR_SCALE)}
+    for i in {8..15}; do
+        local exp="\${color${i}:-\$(rgb_value \$color$(($i - 8)) $THEME_COLOR_SCALE)}"
+        eval "color${i}=$exp"
+    done
 
     if [[ ! "${PREFER_DARK_THEME}" ]]; then
         background=
@@ -235,7 +256,7 @@ refill_colors() {
 # XTheme functions
 # -----------------------------------------------------------------------------
 preview_xtheme() {
-    local color
+    local i color
 
     echo -n "background: "
     printf "\033[38;2;%03d;%03d;%03dm" $(hex_to_rgb $background)
@@ -266,6 +287,29 @@ preview_xtheme() {
     done
 }
 
+find_resource() {
+    local resource="${1}"
+    local name="${2/\~/$HOME}"
+    local path= paths=(
+        "$(dirname "${BASH_SOURCE:-$0}")/${resource}s"
+        "${XTHEME_CACHE}/${resource}s"
+        "$HOME/.local/share/xtheme/${resource}s"
+        "/usr/local/share/xtheme/${resource}s"
+        "/usr/share/xtheme/${resource}s"
+    )
+
+    for path in ${paths[*]}; do
+        path="$path/$name"
+        [[ -e "$path" ]] \
+            && echo "$(realpath "$path")" && return
+    done
+
+    [[ -e "$name" ]] \
+        && echo "$(realpath "$name")" && return
+
+    error "Resource $resource '${2}' not found"
+}
+
 apply() {
     local data
     local srce="${1/\~/$HOME}"
@@ -287,27 +331,6 @@ apply() {
         eval echo -e ${data} >> $dest 2>/dev/null \
             || return $(error "Template '${dest/$HOME/\~}' not save!")
     done < $srce
-}
-
-find_resource() {
-    local resource="${1}"
-    local name="${2/\~/$HOME}"
-    local path= paths=(
-        "$(dirname "${BASH_SOURCE:-$0}")/${resource}s"
-        "${XTHEME_CACHE}/${resource}s"
-        "$HOME/.local/share/xtheme/${resource}s"
-        "/usr/local/share/xtheme/${resource}s"
-        "/usr/share/xtheme/${resource}s"
-        "/"
-    )
-
-    for path in ${paths[*]}; do
-        path="$path/$name"
-        [[ -e "$path" ]] \
-            && echo "$(realpath "$path")" && return
-    done
-
-    error "Resource $resource '${2}' not found"
 }
 
 template() {
@@ -337,7 +360,77 @@ template() {
     return 1
 }
 
+
+# -----------------------------------------------------------------------------
+# Main
 # -----------------------------------------------------------------------------
 mkdir -p "$XTHEME_CACHE"
 
-source "tests/all.sh"; exit 1
+[[ ${RGB_IS_LIB} ]] && return # run as a library
+
+while [ -n "${1}" ]; do
+    case "${1}" in
+        --help|-h)
+            ;;
+        --light|-l)
+            PREFER_DARK_THEME=
+            ;;
+        --dark|-l)
+            PREFER_DARK_THEME=1
+            ;;
+        --image|-s)
+            XTHEME_IMAGE="${2}"
+            XTHEME_NAME=
+            shift
+            ;;
+        --merge|-m)
+            XTHEME_MERGE="${2}"
+            shift
+            ;;
+        --save|-s)
+            XTHEME_SAVE="${2}"
+            shift
+            ;;
+        --install)
+            XTHEME_INSTALL=Yes
+            ;;
+        *)
+            [[ "${1:0:1}" == '-' ]] \
+                && fatal "invalid argument: $1"
+            XTHEME_NAME="${1}"
+            XTHEME_IMAGE=
+            ;;
+    esac
+    shift
+done
+
+clear_colors
+
+if [[ "${XTHEME_NAME}" ]]; then
+    import_theme_colors "$XTHEME_NAME"
+elif [[ "${XTHEME_IMAGE}" ]]; then
+    import_image_colors "$XTHEME_IMAGE"
+else
+    import_xrdb_colors
+fi
+
+if [[ "${XTHEME_MERGE}" ]]; then
+    merge_theme_colors "$XTHEME_MERGE"
+fi
+
+refill_colors
+
+preview_xtheme
+
+if [[ "${XTHEME_SAVE}" ]]; then
+    template colors.sh "$XTHEME_SAVE" > /dev/null \
+        && echo -e "\033[32m[*] theme is saved: $XTHEME_SAVE\033[0m"
+fi
+
+if [[ "${XTHEME_INSTALL}" ]]; then
+    # Templates...
+    template colors.sh
+
+    # Modules...
+    template xrdb
+fi
